### ISSUE TITLE
Mtoc not being recognized as an editor command

### ISSUE THREAD

**Issue by lutzzdias** [hedyhli/markdown-toc.nvim#1]
I've downloaded the plugin following Lazy's specification. The plugin is loaded (confirmed with `:Lazy`) but whenever I run `:Mtoc` I get the following error:

`E492: Not an editor command: Mtoc`

**Comment by hedyhli** [comment]
Did you ensure the setup function gets called? Please share you config.

**Comment by lutzzdias** [comment]
My bad, I misinterpreted Lazy's behavior for calling setup automatically.

I did not provide `opts` as I did not want to change the defaults. This caused Lazy to not automatically call mtoc's setup. Fixed it by adding `config = true` but providing opts would also work.
