### ISSUE TITLE
Second header indent

### ISSUE THREAD

**Issue by Tainted-Fool** [hedyhli/markdown-toc.nvim#4]
Is it possible to increase the indentation of the second header? The first and second header share the same indentation. Here's a screenshot of what I mean:

![image](https://github.com/user-attachments/assets/a3894b92-fe0c-4533-b2f2-9efec9926a32)

This is what I have in my config:

```
return {
    "hedyhli/markdown-toc.nvim",
    ft = "markdown",
    main = "mtoc",
    cmd = "Mtoc",
    keys = {
        { "<leader>ct", "<cmd>Mtoc<CR>", desc = "Insert TOC (mtoc)" },
    },
    opts = {
        toc_list = {
            indent_size = 2,
        },
    },
}
```

**Comment by hedyhli** [comment]
what's the use case for this? If you want something indented, you can increase the heading level.

```
# Heading 1
## Heading 2
### Heading 3
#### Heading 4
```

**Comment by Tainted-Fool** [comment]
The heading level are increased accordingly but when I run `Mtoc` the indentation for header 1 and header 2 are the same:

![image](https://github.com/user-attachments/assets/be933b7d-870f-4f88-b10f-4205885abac1)

It should look something like this:

![image](https://github.com/user-attachments/assets/2d3a045e-5258-409e-842a-7ea117c43b77)

Here's a short gif of what I mean:

![WindowsTerminal_Zo2Oe70ElO](https://github.com/user-attachments/assets/d557690f-75f9-41b3-ac03-09bf75c1a0ad)


Is this the expected result or would it be possible to indent header 2?

**Comment by hedyhli** [comment]
I see what you mean now. Will take a look, thanks!

**Comment by hedyhli** [comment]
This should be fixed now. Let me know if you're running into any other issues.
