### ISSUE TITLE
BUG: Cyrillic in the table of contents does not take into account the lower case of the link text

### ISSUE THREAD

**Issue by anzix** [hedyhli/markdown-toc.nvim#5]
Default settings [markdown-toc.nvim](https://github.com/hedyhli/markdown-toc.nvim) (only changed markers to `markers = "-"`)

This is what it looks like after executing the `Mtoc` command:

```md

<!-- mtoc-start -->

- [Оглавление номер 1](#Оглавление-номер-1)

<!-- mtoc-end -->

## Оглавление номер 1
```

Must be `(#оглавление-номер-1)` that is, the uppercase of the letter `О` to lowercase letter `о`

**Comment by hedyhli** [comment]
https://github.com/hedyhli/markdown-toc.nvim/blob/efd82655ece34059b2259c8cd225ed7efa60e3d4/lua/mtoc/toc.lua#L11

Looks like lua's tolower can't handle UTF-8, we might have some luck with vim functions.

**Comment by hedyhli** [comment]
Let me know if the issue persists.

**Comment by anzix** [comment]
Thank you very much! Everything works

Just in case for those who come here to find out how to do it in the neovim configuration

```lua
return {
   "hedyhli/markdown-toc.nvim",
   ft = "markdown",
   main = "mtoc",
   cmd = "Mtoc",
   keys = {
      { "<leader>ct", "<cmd>Mtoc<CR>", desc = "Insert TOC (mtoc)" },
   },
   opts = {
      toc_list = {
         markers = "-",
         -- Ensure in TOC, title are in Title Case
         item_formatter = function(item, fmtstr)
            local default_formatter = require('mtoc.config').defaults.toc_list.item_formatter
            -- NOTE: Consider using `vim.fn.tolower/toupper` to support letters other than ASCII.
            item.name = item.name:gsub("(%a)([%w_']*)", function(a, b) return vim.fn.toupper(a) .. vim.fn.tolower(b) end)
            return default_formatter(item, fmtstr)
         end,
      },
   },
}
```
